name: test & lint

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      HOSTNAME: localhost
      COOKIE_NAME: placemark
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 25
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Set up environment variables
        run: echo "COOKIE_PASSWORD=${{ secrets.COOKIE_PASSWORD }}" >> $GITHUB_ENV
      - name: Start app
        run: npm run start
      - name: Run tests
        run: npm run tests