name: test & lint

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      HOSTNAME: localhost
      COOKIE_NAME: placemark
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 25
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Set up environment variables
        run: echo "COOKIE_PASSWORD=${{ secrets.COOKIE_PASSWORD }}" >> $GITHUB_ENV
      - name: Start the app
        run: |
          nohup npm run start &  # Replace with the appropriate command for your app
      - name: Install wait-for-it
        run: |
          curl -sS https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > wait-for-it.sh
          chmod +x wait-for-it.sh
      - name: Wait for the app to be ready
        run: |
          ./wait-for-it.sh localhost:3000 --timeout=30 --strict -- echo "App is up and running!"
      - name: Run tests
        run: npm run tests