export const seedData = {
  locations: {
    _model: "Location",
    location_1: {
      title: "Urriðafoss",
      latitude: 63.92506,
      longitude: -20.672678,
      description: "With a flow rate of 360 m³/s, it has the highest average water flow of any waterfall in Iceland.",
      category: "waterfall",
      visibility: "public",
    },
    location_2: {
      title: "Seljalandsfoss",
      latitude: 63.6156,
      longitude: -19.9879,
      description: "The waterfall drops 60 m (197 ft) and is part of the Seljalands River.",
      category: "waterfall",
      visibility: "public",
    },
    location_3: {
      title: "Skógafoss",
      latitude: 63.532111,
      longitude: -19.511139,
      description: "Skógafoss is one of the biggest waterfalls in the country, with a width of 25 metres and a drop of 60 m.",
      category: "waterfall",
      visibility: "public",
    },
    location_4: {
      title: "Jökulsárlón",
      latitude: 64.070278,
      longitude: -16.211667,
      description: "A large glacial lake in southern part of Vatnajökull National Park, the deepest in Iceland.",
      category: "glacier",
      visibility: "public",
    },
    location_5: {
      title: "Reynisfjara",
      latitude: 63.4035,
      longitude: -19.0474,
      description: "A popular black sand beach in southern Iceland near the town of Vík í Mýrdal.",
      category: "beach",
      visibility: "public",
    },
    location_6: {
      title: "Diamond Beach",
      latitude: 64.0437,
      longitude: -16.1963,
      description: "Eindrucksvoller schwarzer Sandstrand mit angespülten großen, glitzernden Eisbergfragmenten.",
      category: "beach",
      visibility: "public",
    },
    location_7: {
      title: "Reykjadalur",
      latitude: 64.0330911,
      longitude: -21.2185979,
      description: "Hot water",
      category: "hot-spring",
      visibility: "public",
    },
  },
};
